spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8080/users
          predicates:
            - Path=/users/**
        - id: product-service
          uri: http://localhost:8082/products
          predicates:
            - Path=/products/**
        - id: order-service
          uri: http://localhost:8081/orders
          predicates:
            - Path=/orders/**
server:
  port: 8083